Algoritmo "Porcentagem"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi
// Descri??o   : APRESENTA 60% DO VALOR DE UM NUMERO
// Autor(a)    : VINICIUS DA CRUZ RODRIGUES
// Data atual  : 07/08/2024
Var
   a: inteiro
   s: real

Inicio
   escreva("Digite um valor: ")
   leia(a)
   s<-a*0.60
   escreva("60% de",a," e igual a",s)


Fimalgoritmo
