Algoritmo "divisão"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi
// Descri??o   : APRESENTA A METADE DE UM NUMERO ALEATORIO
// Autor(a)    : VINICIUS DA CRUZ RODRIGUES
// Data atual  : 07/08/2024
Var
   a: inteiro
   s: real

Inicio
   escreva("Digite um valor: ")
   leia(a)
   s<-a/2
   escreva("A metade de",a," e igual a",s)


Fimalgoritmo
