Algoritmo "PORCENTAGEM"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi
// Descrição   : APRESENTA 25% DO VALOR DE UM NUMERO
// Autor(a)    : VINICIUS DA CRUZ RODRIGUES
// Data atual  : 07/08/2024
Var
   a: inteiro
   s: real

Inicio

   escreva("Digite um valor: ")
   leia(a)
   s<-a*0.25
   escreva("25% de",a," e igual a",s)


Fimalgoritmo
