Algoritmo "TESTANDO ALGORITMO"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : APRESENTAR UMA FRASE
// Autor(a)    : VINICIUS DA CRUZ RODRIGUES
// Data atual  : 07/08/2024
Var
// Seção de Declarações das variáveis 


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
     escreva("Testando algoritmo")

Fimalgoritmo
