Algoritmo "Soma e porcentagem"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi
// Descrição   : APRESENTA 45% DA SOMA DE DOIS VALORES
// Autor(a)    : VINCIUS DA CRUZ RODRIGUES
// Data atual  : 07/08/2024
Var
   a: inteiro
   b: inteiro
   s: real

Inicio
   escreva("Digite um valor: ")
   leia(a)
   escreva("Digite outro valor: ")
   leia(b)
   s<-(a+b)*0.45
   escreva("45% da soma de",a," +",b," e igual a",s)

Fimalgoritmo
