Algoritmo "subtração"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi
// Descrição   : APRESENTA A SUBTRAÇÃO DE DOIS NUMEROS
// Autor(a)    : VINICIUS DA CRUZ RODRIGUES
// Data atual  : 07/08/2024
Var
   a: inteiro
   b: inteiro
   s: real

Inicio
   escreva("Digite um valor: ")
   leia(a)
   escreva("Digite um valor: ")
   leia(b)
   s<-a-b
   escreva("A subtração de",a," e",b," e igual a",s)

Fimalgoritmo
